# Generated by Django 3.2.8 on 2021-10-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_vegetarian', models.BooleanField(null=True)),
                ('is_vegan', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='cook time (minutes)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='prep time (minutes)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.FloatField(null=True)),
                ('modifier', models.CharField(max_length=20, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodboard.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodboard.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='foodboard.IngredientUsage', to='foodboard.Ingredient'),
        ),
    ]
