# Generated by Django 3.2.8 on 2021-10-18 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
