# Generated by Django 3.2.8 on 2021-10-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0002_auto_20211015_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientusage',
            table='ingredient_usage',
        ),
    ]
